worker_processes 4;

error_log syslog:server=unix:/dev/log warn;
pid {{ .DataDir }}/nginx.pid;
daemon off;

events {
    worker_connections  1024;
}

http {
    access_log syslog:server=unix:/dev/log;

    include {{ .AppDir }}/nginx/etc/nginx/mime.types;

    upstream php-handler {
        server unix:{{ .DataDir }}/php.sock;
    }

    client_body_temp_path {{ .DataDir }}/nginx/client_body_temp;
    proxy_temp_path {{ .DataDir }}/nginx/proxy_temp;
    fastcgi_temp_path {{ .DataDir }}/nginx/fastcgi_temp;
    uwsgi_temp_path {{ .DataDir }}/nginx/uwsgi_temp;
    scgi_temp_path {{ .DataDir }}/nginx/scgi_temp;

    server {
        listen unix:{{ .CommonDir }}/web.socket;
        set_real_ip_from unix:;
        server_name localhost;

        root {{ .AppDir }}/php/moodle;
        index index.php;

        client_max_body_size 2G;
        fastcgi_buffers 64 4K;
        fastcgi_read_timeout 600s;
        fastcgi_send_timeout 600s;

        location / {
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ [^/]\.php(/|$) {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_index index.php;
            include fastcgi.conf;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_pass php-handler;
            fastcgi_intercept_errors on;
        }

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2?)$ {
            expires max;
            log_not_found off;
        }
    }
}
